export default function Tweets(props) {

  return (
      tweets.map((tweet, i) => {
      
          return (
            <button 
        onClick={()=> {
          props.setSelectedTweet(tweet);
        }}
        key={i} className="mt-2 border border-gray-200 border  bg-white rounded-xl hover:bg-blue-200 hover:cursor-pointer text-left w-11/12">
          <div className="mx-2 my-1">
            <div className="font-semibold">
              <div className="flex flex-row items-center">
                <img src={tweet.user.profile_image_url} alt="" className="" />
  
                <div className="ml-5">@{tweet.user.screen_name} </div>
  
              </div>
            </div>
            <div className="">
              <p className="font-semibold mt-1"></p> {tweet.text}
            </div>
          </div>
  
        </button>
          )
        }
        
    
  ))}



const tweets = [{
  created_at: 'Wed Oct 20 01:58:09 +0000 2021',
  id: 1450642463694237700,
  id_str: '1450642463694237705',
  text: 'RT @Luhcomentta: Maravilhosa é ela 💙 https://t.co/nh2aq5WPae',
  source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: {
    id: 1354502202614829000,
    id_str: '1354502202614829057',
    name: 'Lima£ 🍪🦂',
    screen_name: 'llimma__',
    location: 'São Paulo, Brasil',
    url: null,
    description: 'Comentarista de reality nas horas vagas haha 💕🗣🍪🦂🏎🎲🐝⚓️',
    translator_type: 'none',
    protected: false,
    verified: false,
    followers_count: 368,
    friends_count: 189,
    listed_count: 1,
    favourites_count: 20911,
    statuses_count: 6415,
    created_at: 'Wed Jan 27 18:51:20 +0000 2021',
    utc_offset: null,
    time_zone: null,
    geo_enabled: false,
    lang: null,
    contributors_enabled: false,
    is_translator: false,
    profile_background_color: 'F5F8FA',
    profile_background_image_url: '',
    profile_background_image_url_https: '',
    profile_background_tile: false,
    profile_link_color: '1DA1F2',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    profile_image_url: 'http://pbs.twimg.com/profile_images/1449772883195174914/aOON7CCx_normal.jpg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/1449772883195174914/aOON7CCx_normal.jpg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/1354502202614829057/1634530605',
    default_profile: true,
    default_profile_image: false,
    following: null,
    follow_request_sent: null,
    notifications: null,
    withheld_in_countries: []
  },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  retweeted_status: {
    created_at: 'Wed Oct 20 01:12:17 +0000 2021',
    id: 1450630920264953900,
    id_str: '1450630920264953857',
    text: 'Maravilhosa é ela 💙 https://t.co/nh2aq5WPae',
    display_text_range: [ 0, 19 ],
    source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1063879428936220700,
      id_str: '1063879428936220672',
      name: '𝚕𝚞𝚊𝚗𝚊° ⚖️',
      screen_name: 'Luhcomentta',
      location: '1°Coríntios 2:9 🦋||⚓|🦂|🏎|🎲',
      url: null,
      description: "• Fan account || Grey's Anatomy and Reality                                                     \n" +
        '• 𝚌𝚊𝚙𝚛𝚒𝚌𝚑𝚎𝚝𝚝𝚎, 𝚍𝚎𝚋𝚘𝚌𝚑𝚊𝚍𝚊 𝚎 𝚋𝚒𝚙𝚘𝚕𝚊𝚛',
      translator_type: 'none',
      protected: false,
      verified: false,
      followers_count: 7601,
      friends_count: 6354,
      listed_count: 9,
      favourites_count: 20156,
      statuses_count: 6239,
      created_at: 'Sat Nov 17 19:39:56 +0000 2018',
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      profile_background_color: 'F5F8FA',
      profile_background_image_url: '',
      profile_background_image_url_https: '',
      profile_background_tile: false,
      profile_link_color: '1DA1F2',
      profile_sidebar_border_color: 'C0DEED',
      profile_sidebar_fill_color: 'DDEEF6',
      profile_text_color: '333333',
      profile_use_background_image: true,
      profile_image_url: 'http://pbs.twimg.com/profile_images/1450165943167037441/vUiKRKeQ_normal.jpg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/1450165943167037441/vUiKRKeQ_normal.jpg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/1063879428936220672/1634239916',
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      withheld_in_countries: []
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    quote_count: 2,
    reply_count: 1,
    retweet_count: 11,
    favorite_count: 103,
    entities: {
      hashtags: [],
      urls: [],
      user_mentions: [],
      symbols: [],
      media: [Array]
    },
    extended_entities: { media: [Array] },
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    filter_level: 'low',
    lang: 'pt'
  },
  is_quote_status: false,
  quote_count: 0,
  reply_count: 0,
  retweet_count: 0,
  favorite_count: 0,
  entities: {
    hashtags: [],
    urls: [],
    user_mentions: [ [Object] ],
    symbols: [],
    media: [ [Object] ]
  },
  extended_entities: { media: [ [Object] ] },
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  filter_level: 'low',
  lang: 'pt',
  timestamp_ms: '1634695089635'
},
{
  created_at: 'Wed Oct 20 01:58:09 +0000 2021',
  id: 1450642463715209200,
  id_str: '1450642463715209218',
  text: 'RT @AGU_SciComm: Editorial Article: ‘Science should align with communication channels to make information accessible’ https://t.co/9c3x1f8v…',
  source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: {
    id: 1432842386019864600,
    id_str: '1432842386019864580',
    name: 'kosher🌋: Jewish geology agent',
    screen_name: 'koshercanoRifka',
    location: 'Midwestern Ope',
    url: 'https://www.youtube.com/channel/UCNmTtdKPhWUdCP5KCzIQjOA',
    description: 'Renaissance Sim, Chassidic volcanology/oceanography student, erratic streamer 🌞| #TheFrumSTEM #KosherGaming #KeepingInTouch | profile art @MellPepper',
    translator_type: 'none',
    protected: false,
    verified: false,
    followers_count: 15,
    friends_count: 296,
    listed_count: 0,
    favourites_count: 255,
    statuses_count: 251,
    created_at: 'Tue Aug 31 23:08:51 +0000 2021',
    utc_offset: null,
    time_zone: null,
    geo_enabled: false,
    lang: null,
    contributors_enabled: false,
    is_translator: false,
    profile_background_color: 'F5F8FA',
    profile_background_image_url: '',
    profile_background_image_url_https: '',
    profile_background_tile: false,
    profile_link_color: '1DA1F2',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    profile_image_url: 'http://pbs.twimg.com/profile_images/1432849082838573059/rfjLJ1Gq_normal.jpg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/1432849082838573059/rfjLJ1Gq_normal.jpg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/1432842386019864580/1630452817',
    default_profile: true,
    default_profile_image: false,
    following: null,
    follow_request_sent: null,
    notifications: null,
    withheld_in_countries: []
  },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  retweeted_status: {
    created_at: 'Wed Oct 20 01:30:03 +0000 2021',
    id: 1450635391195877400,
    id_str: '1450635391195877381',
    text: 'Editorial Article: ‘Science should align with communication channels to make information accessible’… https://t.co/MsX5scIQdY',
    display_text_range: [ 0, 140 ],
    source: '<a href="http://www.falcon.io" rel="nofollow">Falcon Social Media Management </a>',
    truncated: true,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 823586959868264400,
      id_str: '823586959868264449',
      name: 'Sharing Science',
      screen_name: 'AGU_SciComm',
      location: null,
      url: 'http://agu.org/sharingscience',
      description: 'Account of the Sharing Science Program @theAGU. RT & links ≠endorsement.',
      translator_type: 'none',
      protected: false,
      verified: false,
      followers_count: 7637,
      friends_count: 1291,
      listed_count: 148,
      favourites_count: 1598,
      statuses_count: 13166,
      created_at: 'Mon Jan 23 17:43:27 +0000 2017',
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      profile_background_color: '000000',
      profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_tile: false,
      profile_link_color: '6A8739',
      profile_sidebar_border_color: '000000',
      profile_sidebar_fill_color: '000000',
      profile_text_color: '000000',
      profile_use_background_image: false,
      profile_image_url: 'http://pbs.twimg.com/profile_images/1408748556035448840/RnhgphpO_normal.jpg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/1408748556035448840/RnhgphpO_normal.jpg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/823586959868264449/1602165355',
      default_profile: false,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      withheld_in_countries: []
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    extended_tweet: {
      full_text: 'Editorial Article: ‘Science should align with communication channels to make information accessible’ https://t.co/9c3x1f8vyk #SciComm https://t.co/YjqJrGnMTF',
      display_text_range: [Array],
      entities: [Object],
      extended_entities: [Object]
    },
    quote_count: 0,
    reply_count: 0,
    retweet_count: 3,
    favorite_count: 2,
    entities: { hashtags: [], urls: [Array], user_mentions: [], symbols: [] },
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    filter_level: 'low',
    lang: 'en'
  },
  is_quote_status: false,
  quote_count: 0,
  reply_count: 0,
  retweet_count: 0,
  favorite_count: 0,
  entities: { hashtags: [], urls: [], user_mentions: [ [Object] ], symbols: [] },
  favorited: false,
  retweeted: false,
  filter_level: 'low',
  lang: 'en',
  timestamp_ms: '1634695089640'
},
{
  created_at: 'Wed Oct 20 01:58:09 +0000 2021',
  id: 1450642463874379800,
  id_str: '1450642463874379777',
  text: 'RT @Kasem75660674: Mesing pegola digin jadi kasi panas Dolo 😂😂🤭 https://t.co/AJ906LDpHp',
  source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: {
    id: 1301540934975328300,
    id_str: '1301540934975328257',
    name: 'panggilan darurat',
    screen_name: 'modaluang',
    location: null,
    url: null,
    description: 'mati gaya',
    translator_type: 'none',
    protected: false,
    verified: false,
    followers_count: 213,
    friends_count: 659,
    listed_count: 0,
    favourites_count: 95,
    statuses_count: 1013,
    created_at: 'Thu Sep 03 15:22:13 +0000 2020',
    utc_offset: null,
    time_zone: null,
    geo_enabled: false,
    lang: null,
    contributors_enabled: false,
    is_translator: false,
    profile_background_color: 'F5F8FA',
    profile_background_image_url: '',
    profile_background_image_url_https: '',
    profile_background_tile: false,
    profile_link_color: '1DA1F2',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    profile_image_url: 'http://pbs.twimg.com/profile_images/1301653632681566208/rlcEAfll_normal.jpg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/1301653632681566208/rlcEAfll_normal.jpg',
    default_profile: true,
    default_profile_image: false,
    following: null,
    follow_request_sent: null,
    notifications: null,
    withheld_in_countries: []
  },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  retweeted_status: {
    created_at: 'Sun Oct 17 17:48:52 +0000 2021',
    id: 1449794554144510000,
    id_str: '1449794554144509954',
    text: 'Mesing pegola digin jadi kasi panas Dolo 😂😂🤭 https://t.co/AJ906LDpHp',
    display_text_range: [ 0, 44 ],
    source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1430897037269033000,
      id_str: '1430897037269032971',
      name: 'Kasem',
      screen_name: 'Kasem75660674',
      location: 'Papua Barat',
      url: null,
      description: 'cuma cari ikan puri\n' +
        '\n' +
        '\n' +
        '\n' +
        'mkw ada kha 😂 yg bisa pake 150 \n' +
        '1 mlm sj \n' +
        'cat kalo mau \n' +
        '\n' +
        'sy jatang Bukan betina 🖕👊',
      translator_type: 'none',
      protected: false,
      verified: false,
      followers_count: 3454,
      friends_count: 230,
      listed_count: 1,
      favourites_count: 1014,
      statuses_count: 193,
      created_at: 'Thu Aug 26 14:17:17 +0000 2021',
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      profile_background_color: 'F5F8FA',
      profile_background_image_url: '',
      profile_background_image_url_https: '',
      profile_background_tile: false,
      profile_link_color: '1DA1F2',
      profile_sidebar_border_color: 'C0DEED',
      profile_sidebar_fill_color: 'DDEEF6',
      profile_text_color: '333333',
      profile_use_background_image: true,
      profile_image_url: 'http://pbs.twimg.com/profile_images/1450491191212986369/Izs4odvM_normal.jpg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/1450491191212986369/Izs4odvM_normal.jpg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/1430897037269032971/1634326918',
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      withheld_in_countries: []
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    quote_count: 0,
    reply_count: 4,
    retweet_count: 57,
    favorite_count: 93,
    entities: {
      hashtags: [],
      urls: [],
      user_mentions: [],
      symbols: [],
      media: [Array]
    },
    extended_entities: { media: [Array] },
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    filter_level: 'low',
    lang: 'in'
  },
  is_quote_status: false,
  quote_count: 0,
  reply_count: 0,
  retweet_count: 0,
  favorite_count: 0,
  entities: {
    hashtags: [],
    urls: [],
    user_mentions: [ [Object] ],
    symbols: [],
    media: [ [Object] ]
  },
  extended_entities: { media: [ [Object] ] },
  favorited: false,
  retweeted: false,
  possibly_sensitive: true,
  filter_level: 'low',
  lang: 'in',
  timestamp_ms: '1634695089678'
},
{
  created_at: 'Wed Oct 20 01:58:09 +0000 2021',
  id: 1450642463215915000,
  id_str: '1450642463215915015',
  text: '오 마이 갓.... 소 큩 https://t.co/f4XW4mz1DS',
  display_text_range: [ 0, 14 ],
  source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: {
    id: 1297431661294977000,
    id_str: '1297431661294977024',
    name: '꿀베',
    screen_name: 'BONITO_XIN',
    location: 'DM❌(컵홀더 총대 관련 문의 디엠⭕️)',
    url: 'https://asked.kr/judy1st',
    description: '팬 어카운트 for #BTS',
    translator_type: 'none',
    protected: false,
    verified: false,
    followers_count: 740,
    friends_count: 238,
    listed_count: 59,
    favourites_count: 6839,
    statuses_count: 36933,
    created_at: 'Sun Aug 23 07:13:17 +0000 2020',
    utc_offset: null,
    time_zone: null,
    geo_enabled: false,
    lang: null,
    contributors_enabled: false,
    is_translator: false,
    profile_background_color: 'F5F8FA',
    profile_background_image_url: '',
    profile_background_image_url_https: '',
    profile_background_tile: false,
    profile_link_color: '1DA1F2',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    profile_image_url: 'http://pbs.twimg.com/profile_images/1450072101168173057/CIeiTe_C_normal.jpg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/1450072101168173057/CIeiTe_C_normal.jpg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/1297431661294977024/1634560701',
    default_profile: true,
    default_profile_image: false,
    following: null,
    follow_request_sent: null,
    notifications: null,
    withheld_in_countries: []
  },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  quote_count: 0,
  reply_count: 0,
  retweet_count: 0,
  favorite_count: 0,
  entities: {
    hashtags: [],
    urls: [],
    user_mentions: [],
    symbols: [],
    media: [ [Object] ]
  },
  extended_entities: { media: [ [Object], [Object] ] },
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  filter_level: 'low',
  lang: 'ko',
  timestamp_ms: '1634695089521'
},
{
  created_at: 'Wed Oct 20 01:58:09 +0000 2021',
  id: 1450642463949869000,
  id_str: '1450642463949869057',
  text: 'RT @actrssglamfeed: Pranitha🔥🔥 https://t.co/vkFOz9j8hx',
  source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: {
    id: 1410900194346950700,
    id_str: '1410900194346950660',
    name: '𝐇𝐨𝐭 𝐀𝐜𝐭𝐫𝐞𝐬𝐬',
    screen_name: 'Actress_culy',
    location: null,
    url: 'http://bit.ly/3jQvaKp',
    description: null,
    translator_type: 'none',
    protected: false,
    verified: false,
    followers_count: 14,
    friends_count: 123,
    listed_count: 0,
    favourites_count: 1417,
    statuses_count: 108,
    created_at: 'Fri Jul 02 09:56:46 +0000 2021',
    utc_offset: null,
    time_zone: null,
    geo_enabled: false,
    lang: null,
    contributors_enabled: false,
    is_translator: false,
    profile_background_color: 'F5F8FA',
    profile_background_image_url: '',
    profile_background_image_url_https: '',
    profile_background_tile: false,
    profile_link_color: '1DA1F2',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    profile_image_url: 'http://pbs.twimg.com/profile_images/1450328049749090308/yOu71ul__normal.jpg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/1450328049749090308/yOu71ul__normal.jpg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/1410900194346950660/1634617786',
    default_profile: true,
    default_profile_image: false,
    following: null,
    follow_request_sent: null,
    notifications: null,
    withheld_in_countries: []
  },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  retweeted_status: {
    created_at: 'Tue Oct 19 05:41:44 +0000 2021',
    id: 1450336343804964900,
    id_str: '1450336343804964865',
    text: 'Pranitha🔥🔥 https://t.co/vkFOz9j8hx',
    display_text_range: [ 0, 10 ],
    source: '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 884093586844799000,
      id_str: '884093586844798976',
      name: 'GlamFeed',
      screen_name: 'actrssglamfeed',
      location: null,
      url: null,
      description: 'Posting it in HQ 🔥💥 Glam World ♥️ Actress ❤️',
      translator_type: 'none',
      protected: false,
      verified: false,
      followers_count: 88325,
      friends_count: 39,
      listed_count: 90,
      favourites_count: 56072,
      statuses_count: 9399,
      created_at: 'Sun Jul 09 16:55:11 +0000 2017',
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      profile_background_color: 'F5F8FA',
      profile_background_image_url: '',
      profile_background_image_url_https: '',
      profile_background_tile: false,
      profile_link_color: '1DA1F2',
      profile_sidebar_border_color: 'C0DEED',
      profile_sidebar_fill_color: 'DDEEF6',
      profile_text_color: '333333',
      profile_use_background_image: true,
      profile_image_url: 'http://pbs.twimg.com/profile_images/1439675838186754050/7sGx5sDa_normal.jpg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/1439675838186754050/7sGx5sDa_normal.jpg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/884093586844798976/1632121146',
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      withheld_in_countries: []
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    quote_count: 0,
    reply_count: 0,
    retweet_count: 74,
    favorite_count: 388,
    entities: {
      hashtags: [],
      urls: [],
      user_mentions: [],
      symbols: [],
      media: [Array]
    },
    extended_entities: { media: [Array] },
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    filter_level: 'low',
    lang: 'en'
  },
  is_quote_status: false,
  quote_count: 0,
  reply_count: 0,
  retweet_count: 0,
  favorite_count: 0,
  entities: {
    hashtags: [],
    urls: [],
    user_mentions: [ [Object] ],
    symbols: [],
    media: [ [Object] ]
  },
  extended_entities: { media: [ [Object] ] },
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  filter_level: 'low',
  lang: 'en',
  timestamp_ms: '1634695089696'
},
{
  created_at: 'Wed Oct 20 01:58:09 +0000 2021',
  id: 1450642463866032000,
  id_str: '1450642463866032130',
  text: 'RT @SebGatica: #مدبوغ_بارك   \n' +
    '#حملة_مقاطعة_العربية_للعود \n' +
    'اجمل الجلسات والسهرات الفاخرة والحمام المغربي \n' +
    'العاملات مغربية سعوديه بنانيه مصري…',
  source: '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: {
    id: 2269797940,
    id_str: '2269797940',
    name: 'لؤلـــؤ ',
    screen_name: 'loolo2510',
    location: null,
    url: null,
    description: null,
    translator_type: 'none',
    protected: false,
    verified: false,
    followers_count: 47,
    friends_count: 70,
    listed_count: 0,
    favourites_count: 2797,
    statuses_count: 5580,
    created_at: 'Thu Jan 09 00:03:07 +0000 2014',
    utc_offset: null,
    time_zone: null,
    geo_enabled: false,
    lang: null,
    contributors_enabled: false,
    is_translator: false,
    profile_background_color: 'C0DEED',
    profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_tile: false,
    profile_link_color: '1DA1F2',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    profile_image_url: 'http://pbs.twimg.com/profile_images/421657642957012992/atgVPGGN_normal.jpeg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/421657642957012992/atgVPGGN_normal.jpeg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/2269797940/1389226154',
    default_profile: true,
    default_profile_image: false,
    following: null,
    follow_request_sent: null,
    notifications: null,
    withheld_in_countries: []
  },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  retweeted_status: {
    created_at: 'Wed Oct 20 01:56:19 +0000 2021',
    id: 1450642003054809000,
    id_str: '1450642003054809092',
    text: '#مدبوغ_بارك   \n' +
      '#حملة_مقاطعة_العربية_للعود \n' +
      'اجمل الجلسات والسهرات الفاخرة والحمام المغربي \n' +
      'العاملات مغربية سعوديه بن… https://t.co/9sOUFoDwhp',
    display_text_range: [ 0, 140 ],
    source: '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    truncated: true,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 14288807,
      id_str: '14288807',
      name: 'ام زين منسقة تدليك وسهرات خاصة خدمه 24ساعه',
      screen_name: 'SebGatica',
      location: 'المملكة العربية السعودية',
      url: 'http://wa.me/966592269176',
      description: '‏منسقة ام زين لحجز افخم الجلسات تدليك كامل الجسم \n' +
        'الممسجات مغربية سعوديه مصريه لبنانية فلبينيه للتواصل واتساب http://wa.me/966592269176',
      translator_type: 'none',
      protected: false,
      verified: false,
      followers_count: 741,
      friends_count: 809,
      listed_count: 24,
      favourites_count: 92,
      statuses_count: 4590,
      created_at: 'Thu Apr 03 00:09:01 +0000 2008',
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      profile_background_color: '1A1B1F',
      profile_background_image_url: 'http://abs.twimg.com/images/themes/theme9/bg.gif',
      profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme9/bg.gif',
      profile_background_tile: false,
      profile_link_color: '2FC2EF',
      profile_sidebar_border_color: '181A1E',
      profile_sidebar_fill_color: '252429',
      profile_text_color: '666666',
      profile_use_background_image: true,
      profile_image_url: 'http://pbs.twimg.com/profile_images/1449536567463321603/SGR6OiIE_normal.jpg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/1449536567463321603/SGR6OiIE_normal.jpg',
      default_profile: false,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      withheld_in_countries: []
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    extended_tweet: {
      full_text: '#مدبوغ_بارك   \n' +
        '#حملة_مقاطعة_العربية_للعود \n' +
        'اجمل الجلسات والسهرات الفاخرة والحمام المغربي \n' +
        'العاملات مغربية سعوديه بنانيه مصريه\n' +
        'حجوزات فوريه للتواصل واتساب \n' +
        'منسقةhttps://t.co/W32lWrRE1B https://t.co/cf8aVV4SvP',
      display_text_range: [Array],
      entities: [Object],
      extended_entities: [Object]
    },
    quote_count: 0,
    reply_count: 0,
    retweet_count: 29,
    favorite_count: 14,
    entities: {
      hashtags: [Array],
      urls: [Array],
      user_mentions: [],
      symbols: []
    },
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    filter_level: 'low',
    lang: 'ar'
  },
  is_quote_status: false,
  quote_count: 0,
  reply_count: 0,
  retweet_count: 0,
  favorite_count: 0,
  entities: {
    hashtags: [ [Object], [Object] ],
    urls: [],
    user_mentions: [ [Object] ],
    symbols: []
  },
  favorited: false,
  retweeted: false,
  filter_level: 'low',
  lang: 'ar',
  timestamp_ms: '1634695089676'
}]



