export default function Tweets(props) {

  return (
      tweets.map((tweet, i) => {
      
          return (
            <button 
        onClick={()=> {
          props.setSelectedTweet(tweet);
        }}
        key={i} className="mt-2 border border-gray-200 border  bg-white rounded-xl hover:bg-blue-200 hover:cursor-pointer text-left w-11/12">
          <div className="mx-2 my-1">
            <div className="font-semibold">
              <div className="flex flex-row items-center">
                <img src={tweet.user.profile_image_url} alt="" className="" />
  
                <div className="ml-5">@{tweet.user.screen_name} </div>
  
              </div>
            </div>
            <div className="">
              <p className="font-semibold mt-1"></p> {tweet.text}
            </div>
          </div>
  
        </button>
          )
        }
        
    
  ))}



const tweets = [{
  created_at: 'Wed Oct 20 02:51:45 +0000 2021',
  id: 1450655952756043800,
  id_str: '1450655952756043776',
  text: 'RT @Babbeslut: my delicious pussy is horny happy favourite 😈 https://t.co/4wEoeHBlqL',
  source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: {
    id: 1166468421808087000,
    id_str: '1166468421808087041',
    name: '涼風',
    screen_name: 'omeko191940',
    location: null,
    url: null,
    description: '初めましてよろしくお願いします。',
    translator_type: 'none',
    protected: false,
    verified: false,
    followers_count: 33,
    friends_count: 79,
    listed_count: 11,
    favourites_count: 8254,
    statuses_count: 2797,
    created_at: 'Tue Aug 27 21:52:28 +0000 2019',
    utc_offset: null,
    time_zone: null,
    geo_enabled: false,
    lang: null,
    contributors_enabled: false,
    is_translator: false,
    profile_background_color: 'F5F8FA',
    profile_background_image_url: '',
    profile_background_image_url_https: '',
    profile_background_tile: false,
    profile_link_color: '1DA1F2',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    profile_image_url: 'http://pbs.twimg.com/profile_images/1383203883988578304/j9zghAHD_normal.jpg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/1383203883988578304/j9zghAHD_normal.jpg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/1166468421808087041/1567026923',
    default_profile: true,
    default_profile_image: false,
    following: null,
    follow_request_sent: null,
    notifications: null,
    withheld_in_countries: []
  },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  retweeted_status: {
    created_at: 'Tue Oct 19 20:33:26 +0000 2021',
    id: 1450560744429289500,
    id_str: '1450560744429289478',
    text: 'my delicious pussy is horny 😈 https://t.co/4wEoeHBlqL',
    display_text_range: [ 0, 29 ],
    source: '<a href="https://studio.twitter.com" rel="nofollow">Twitter Media Studio</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1325683808910401500,
      id_str: '1325683808910401537',
      name: 'B a b e',
      screen_name: 'Babbeslut',
      location: 'United Kingdom',
      url: 'http://hornyslut.co',
      description: '• Possessed by the demon of masturbation♥️\n' +
        '• Explicit content🔞\n' +
        '• Turn on notifications🔔',
      translator_type: 'none',
      protected: false,
      verified: false,
      followers_count: 254218,
      friends_count: 13,
      listed_count: 1098,
      favourites_count: 20,
      statuses_count: 189,
      created_at: 'Mon Nov 09 06:17:12 +0000 2020',
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      profile_background_color: 'F5F8FA',
      profile_background_image_url: '',
      profile_background_image_url_https: '',
      profile_background_tile: false,
      profile_link_color: '1DA1F2',
      profile_sidebar_border_color: 'C0DEED',
      profile_sidebar_fill_color: 'DDEEF6',
      profile_text_color: '333333',
      profile_use_background_image: true,
      profile_image_url: 'http://pbs.twimg.com/profile_images/1326753208811843584/M-YxxrHl_normal.jpg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/1326753208811843584/M-YxxrHl_normal.jpg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/1325683808910401537/1605051398',
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      withheld_in_countries: []
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    quote_count: 6,
    reply_count: 39,
    retweet_count: 566,
    favorite_count: 4178,
    entities: {
      hashtags: [],
      urls: [],
      user_mentions: [],
      symbols: [],
      media: [Array]
    },
    extended_entities: { media: [Array] },
    favorited: false,
    retweeted: false,
    possibly_sensitive: true,
    filter_level: 'low',
    lang: 'en'
  },
  is_quote_status: false,
  quote_count: 0,
  reply_count: 0,
  retweet_count: 0,
  favorite_count: 0,
  entities: {
    hashtags: [],
    urls: [],
    user_mentions: [ [Object] ],
    symbols: [],
    media: [ [Object] ]
  },
  extended_entities: { media: [ [Object] ] },
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  filter_level: 'low',
  lang: 'en',
  timestamp_ms: '1634698305678'
},
{
  created_at: 'Wed Oct 20 02:51:45 +0000 2021',
  id: 1450655952160497700,
  id_str: '1450655952160497669',
  text: '@HwanniePromotes Done tysm 💗 https://t.co/h972B28RH2',
  display_text_range: [ 17, 28 ],
  source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
  truncated: false,
  in_reply_to_status_id: 1450627791943176200,
  in_reply_to_status_id_str: '1450627791943176196',
  in_reply_to_user_id: 1363765131172221000,
  in_reply_to_user_id_str: '1363765131172220933',
  in_reply_to_screen_name: 'HwanniePromotes',
  user: {
    id: 1420732392029884400,
    id_str: '1420732392029884416',
    name: 'BIG WIN$ CUTIE$🍀🍀🇵🇭',
    screen_name: 'Luna39214172',
    location: null,
    url: null,
    description: '#calixfam #CleiCakes #JayFam\n' +
      '#marurupok #ZFam\n' +
      '#famirise\n' +
      '#notianne\n' +
      '#eivanaluvs\n' +
      '#Autumnfam \n' +
      '#bibblees\n' +
      '#cuthysfam\n' +
      '#pammiesfam\n' +
      '#sarawatlism #faMerry\n' +
      '#yunafamii',
    translator_type: 'none',
    protected: false,
    verified: false,
    followers_count: 916,
    friends_count: 5003,
    listed_count: 3,
    favourites_count: 47595,
    statuses_count: 83035,
    created_at: 'Thu Jul 29 13:07:11 +0000 2021',
    utc_offset: null,
    time_zone: null,
    geo_enabled: false,
    lang: null,
    contributors_enabled: false,
    is_translator: false,
    profile_background_color: 'F5F8FA',
    profile_background_image_url: '',
    profile_background_image_url_https: '',
    profile_background_tile: false,
    profile_link_color: '1DA1F2',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    profile_image_url: 'http://pbs.twimg.com/profile_images/1443855659615748096/t_oUGmsU_normal.jpg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/1443855659615748096/t_oUGmsU_normal.jpg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/1420732392029884416/1633077031',
    default_profile: true,
    default_profile_image: false,
    following: null,
    follow_request_sent: null,
    notifications: null,
    withheld_in_countries: []
  },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  quote_count: 0,
  reply_count: 0,
  retweet_count: 0,
  favorite_count: 0,
  entities: {
    hashtags: [],
    urls: [],
    user_mentions: [ [Object] ],
    symbols: [],
    media: [ [Object] ]
  },
  extended_entities: { media: [ [Object] ] },
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  filter_level: 'low',
  lang: 'en',
  timestamp_ms: '1634698305536'
},
{
  created_at: 'Wed Oct 20 02:51:45 +0000 2021',
  id: 1450655952483541000,
  id_str: '1450655952483541000',
  text: 'RT @wonietiny: 🗓 20/10\n' +
    '⏰ 9:00pm - 11:00pm kst\n' +
    '\n' +
    '6:00am - 8:00am 🇸🇻🇭🇳🇳🇮🇬🇹🇨🇷🇧🇿\n' +
    '7:00am - 9:00am 🇨🇴🇪🇨🇵🇪🇵🇦🇲🇽\n' +
    '8:00am - 10:00am 🇩🇴🇵🇷🇻🇪🇧🇴🇨🇺\n' +
    '9:00am -…',
  source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: {
    id: 1302499162039214000,
    id_str: '1302499162039214080',
    name: 'DIMENSION: LUZ 🔟🗓',
    screen_name: 'SilvinaLuzCorr2',
    location: 'Bolivia',
    url: null,
    description: 'ENGENE',
    translator_type: 'none',
    protected: false,
    verified: false,
    followers_count: 76,
    friends_count: 290,
    listed_count: 0,
    favourites_count: 9446,
    statuses_count: 4412,
    created_at: 'Sun Sep 06 06:50:01 +0000 2020',
    utc_offset: null,
    time_zone: null,
    geo_enabled: false,
    lang: null,
    contributors_enabled: false,
    is_translator: false,
    profile_background_color: 'F5F8FA',
    profile_background_image_url: '',
    profile_background_image_url_https: '',
    profile_background_tile: false,
    profile_link_color: '1DA1F2',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    profile_image_url: 'http://pbs.twimg.com/profile_images/1448646474296750082/UGAIcn5s_normal.jpg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/1448646474296750082/UGAIcn5s_normal.jpg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/1302499162039214080/1633994539',
    default_profile: true,
    default_profile_image: false,
    following: null,
    follow_request_sent: null,
    notifications: null,
    withheld_in_countries: []
  },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  retweeted_status: {
    created_at: 'Tue Oct 19 23:15:09 +0000 2021',
    id: 1450601443803766800,
    id_str: '1450601443803766786',
    text: '🗓 20/10\n' +
      '⏰ 9:00pm - 11:00pm kst\n' +
      '\n' +
      '6:00am - 8:00am 🇸🇻🇭🇳🇳🇮🇬🇹🇨🇷🇧🇿\n' +
      '7:00am - 9:00am 🇨🇴🇪🇨🇵🇪🇵🇦🇲🇽\n' +
      '8:00am - 10:00am 🇩🇴🇵🇷🇻🇪🇧🇴🇨🇺… https://t.co/jLUjeoa9vd',
    source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
    truncated: true,
    in_reply_to_status_id: 1450601440620261400,
    in_reply_to_status_id_str: '1450601440620261378',
    in_reply_to_user_id: 1285076394557476900,
    in_reply_to_user_id_str: '1285076394557476866',
    in_reply_to_screen_name: 'wonietiny',
    user: {
      id: 1285076394557476900,
      id_str: '1285076394557476866',
      name: 'søl',
      screen_name: 'wonietiny',
      location: ' ͏͏ ͏͏she/her ',
      url: 'https://wonietiny.carrd.co/',
      description: '#ENHYPEN 4th gen hot icon',
      translator_type: 'none',
      protected: false,
      verified: false,
      followers_count: 12937,
      friends_count: 5167,
      listed_count: 88,
      favourites_count: 45786,
      statuses_count: 27833,
      created_at: 'Mon Jul 20 04:57:55 +0000 2020',
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      profile_background_color: 'F5F8FA',
      profile_background_image_url: '',
      profile_background_image_url_https: '',
      profile_background_tile: false,
      profile_link_color: '1DA1F2',
      profile_sidebar_border_color: 'C0DEED',
      profile_sidebar_fill_color: 'DDEEF6',
      profile_text_color: '333333',
      profile_use_background_image: true,
      profile_image_url: 'http://pbs.twimg.com/profile_images/1450468295866454040/oAwasaMu_normal.jpg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/1450468295866454040/oAwasaMu_normal.jpg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/1285076394557476866/1633827245',
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      withheld_in_countries: []
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    quoted_status_id: 1450464357326991400,
    quoted_status_id_str: '1450464357326991362',
    quoted_status: {
      created_at: 'Tue Oct 19 14:10:25 +0000 2021',
      id: 1450464357326991400,
      id_str: '1450464357326991362',
      text: 'ENGENEs! Join us tomorrow (October 20, 9PM - 11PM KST) on @STATIONHEAD in our efforts to increase our streams durin… https://t.co/jQbBkLya3M',
      display_text_range: [Array],
      source: '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
      truncated: true,
      in_reply_to_status_id: null,
      in_reply_to_status_id_str: null,
      in_reply_to_user_id: null,
      in_reply_to_user_id_str: null,
      in_reply_to_screen_name: null,
      user: [Object],
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      extended_tweet: [Object],
      quote_count: 58,
      reply_count: 21,
      retweet_count: 2378,
      favorite_count: 6260,
      entities: [Object],
      favorited: false,
      retweeted: false,
      possibly_sensitive: false,
      filter_level: 'low',
      lang: 'en'
    },
    quoted_status_permalink: {
      url: 'https://t.co/IEDaUwcV3h',
      expanded: 'https://twitter.com/enhypenupdates/status/1450464357326991362?t=SEZvlqJQKDH5gE-z_uvHfw&s=19',
      display: 'twitter.com/enhypenupdates…'
    },
    is_quote_status: true,
    extended_tweet: {
      full_text: '🗓 20/10\n' +
        '⏰ 9:00pm - 11:00pm kst\n' +
        '\n' +
        '6:00am - 8:00am 🇸🇻🇭🇳🇳🇮🇬🇹🇨🇷🇧🇿\n' +
        '7:00am - 9:00am 🇨🇴🇪🇨🇵🇪🇵🇦🇲🇽\n' +
        '8:00am - 10:00am 🇩🇴🇵🇷🇻🇪🇧🇴🇨🇺\n' +
        '9:00am - 11:00am 🇧🇷🇦🇷🇺🇾🇨🇱🇵🇾\n' +
        '2:00pm - 4:00pm 🇪🇸\n' +
        '\n' +
        '• Para hacer stream en STATIONHEAD se necesita spotify premium\n' +
        '\n' +
        '©antlbelift \n' +
        'https://t.co/IEDaUwcV3h',
      display_text_range: [Array],
      entities: [Object]
    },
    quote_count: 0,
    reply_count: 0,
    retweet_count: 9,
    favorite_count: 12,
    entities: { hashtags: [], urls: [Array], user_mentions: [], symbols: [] },
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    filter_level: 'low',
    lang: 'en'
  },
  quoted_status_id: 1450464357326991400,
  quoted_status_id_str: '1450464357326991362',
  quoted_status: {
    created_at: 'Tue Oct 19 14:10:25 +0000 2021',
    id: 1450464357326991400,
    id_str: '1450464357326991362',
    text: 'ENGENEs! Join us tomorrow (October 20, 9PM - 11PM KST) on @STATIONHEAD in our efforts to increase our streams durin… https://t.co/jQbBkLya3M',
    display_text_range: [ 0, 140 ],
    source: '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    truncated: true,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 835440693870932000,
      id_str: '835440693870931973',
      name: 'ENHYPEN UPDATES',
      screen_name: 'enhypenupdates',
      location: 'Visit our Carrd →',
      url: 'https://enhypenconnect.crd.co/',
      description: "The Biggest and Prime ENHYPEN International Fanbase and Your #1 Source of ENHYPEN's Daily News and Updates | 📧: contactenhypenupdates@gmail.com",
      translator_type: 'none',
      protected: false,
      verified: false,
      followers_count: 473688,
      friends_count: 33,
      listed_count: 4731,
      favourites_count: 2412,
      statuses_count: 13669,
      created_at: 'Sat Feb 25 10:45:57 +0000 2017',
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      profile_background_color: '000000',
      profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_tile: false,
      profile_link_color: '8B0000',
      profile_sidebar_border_color: '000000',
      profile_sidebar_fill_color: '000000',
      profile_text_color: '000000',
      profile_use_background_image: false,
      profile_image_url: 'http://pbs.twimg.com/profile_images/1439544403782094851/U-3oU_vm_normal.jpg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/1439544403782094851/U-3oU_vm_normal.jpg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/835440693870931973/1633054311',
      default_profile: false,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      withheld_in_countries: []
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    extended_tweet: {
      full_text: 'ENGENEs! Join us tomorrow (October 20, 9PM - 11PM KST) on @STATIONHEAD in our efforts to increase our streams during this Billboard tracking week.\n' +
        '\n' +
        "This is in collaboration with @BILLBOARDBELIFT and @EN_onSpotify. Let's go big on Billboard charts! 🥳🤍\n" +
        '\n' +
        '@ENHYPEN_members @ENHYPEN https://t.co/hA4f1hvvZO',
      display_text_range: [Array],
      entities: [Object],
      extended_entities: [Object]
    },
    quote_count: 58,
    reply_count: 21,
    retweet_count: 2378,
    favorite_count: 6260,
    entities: {
      hashtags: [],
      urls: [Array],
      user_mentions: [Array],
      symbols: []
    },
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    filter_level: 'low',
    lang: 'en'
  },
  quoted_status_permalink: {
    url: 'https://t.co/IEDaUwcV3h',
    expanded: 'https://twitter.com/enhypenupdates/status/1450464357326991362?t=SEZvlqJQKDH5gE-z_uvHfw&s=19',
    display: 'twitter.com/enhypenupdates…'
  },
  is_quote_status: true,
  quote_count: 0,
  reply_count: 0,
  retweet_count: 0,
  favorite_count: 0,
  entities: { hashtags: [], urls: [], user_mentions: [ [Object] ], symbols: [] },
  favorited: false,
  retweeted: false,
  filter_level: 'low',
  lang: 'en',
  timestamp_ms: '1634698305613'
},
{
  created_at: 'Wed Oct 20 02:51:45 +0000 2021',
  id: 1450655952764551200,
  id_str: '1450655952764551168',
  text: "RT @sunsunflake: SUNOO'S WAIST WHAT THE HELL https://t.co/I94NoREAax",
  source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: {
    id: 1311008646491525000,
    id_str: '1311008646491525121',
    name: 'María',
    screen_name: 'Mara78186949',
    location: null,
    url: null,
    description: null,
    translator_type: 'none',
    protected: false,
    verified: false,
    followers_count: 11,
    friends_count: 366,
    listed_count: 1,
    favourites_count: 27791,
    statuses_count: 15539,
    created_at: 'Tue Sep 29 18:23:24 +0000 2020',
    utc_offset: null,
    time_zone: null,
    geo_enabled: false,
    lang: null,
    contributors_enabled: false,
    is_translator: false,
    profile_background_color: 'F5F8FA',
    profile_background_image_url: '',
    profile_background_image_url_https: '',
    profile_background_tile: false,
    profile_link_color: '1DA1F2',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    profile_image_url: 'http://pbs.twimg.com/profile_images/1336442482947739658/zPJQJylS_normal.jpg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/1336442482947739658/zPJQJylS_normal.jpg',
    default_profile: true,
    default_profile_image: false,
    following: null,
    follow_request_sent: null,
    notifications: null,
    withheld_in_countries: []
  },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  retweeted_status: {
    created_at: 'Tue Oct 19 08:50:35 +0000 2021',
    id: 1450383867928453000,
    id_str: '1450383867928453122',
    text: "SUNOO'S WAIST WHAT THE HELL https://t.co/I94NoREAax",
    display_text_range: [ 0, 27 ],
    source: '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1295983209000312800,
      id_str: '1295983209000312834',
      name: 'namu ia HIYYIH DEBUT',
      screen_name: 'sunsunflake',
      location: ' bts ',
      url: 'https://woniflake.carrd.co/',
      description: 'she/her, minor, 🏳️‍🌈— RPS',
      translator_type: 'none',
      protected: false,
      verified: false,
      followers_count: 8537,
      friends_count: 744,
      listed_count: 58,
      favourites_count: 61817,
      statuses_count: 60416,
      created_at: 'Wed Aug 19 07:17:41 +0000 2020',
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      profile_background_color: 'F5F8FA',
      profile_background_image_url: '',
      profile_background_image_url_https: '',
      profile_background_tile: false,
      profile_link_color: '1DA1F2',
      profile_sidebar_border_color: 'C0DEED',
      profile_sidebar_fill_color: 'DDEEF6',
      profile_text_color: '333333',
      profile_use_background_image: true,
      profile_image_url: 'http://pbs.twimg.com/profile_images/1429695764201017355/7rGZC2x-_normal.jpg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/1429695764201017355/7rGZC2x-_normal.jpg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/1295983209000312834/1629701006',
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      withheld_in_countries: []
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    quote_count: 156,
    reply_count: 16,
    retweet_count: 430,
    favorite_count: 2867,
    entities: {
      hashtags: [],
      urls: [],
      user_mentions: [],
      symbols: [],
      media: [Array]
    },
    extended_entities: { media: [Array] },
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    filter_level: 'low',
    lang: 'en'
  },
  is_quote_status: false,
  quote_count: 0,
  reply_count: 0,
  retweet_count: 0,
  favorite_count: 0,
  entities: {
    hashtags: [],
    urls: [],
    user_mentions: [ [Object] ],
    symbols: [],
    media: [ [Object] ]
  },
  extended_entities: { media: [ [Object] ] },
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  filter_level: 'low',
  lang: 'en',
  timestamp_ms: '1634698305680'
},
{
  created_at: 'Wed Oct 20 02:51:45 +0000 2021',
  id: 1450655952273825800,
  id_str: '1450655952273825792',
  text: 'Brandy... Now dont give her Kiely Williams flashbacks  #Queens #QueensABC https://t.co/XE2hs0kdRf',
  display_text_range: [ 0, 73 ],
  source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: {
    id: 1397431274160144400,
    id_str: '1397431274160144385',
    name: 'YoungRichSkinny',
    screen_name: 'YoungRichSkinn2',
    location: 'Messy Queen Island ',
    url: 'http://YoungRichSkinny.Org',
    description: 'backup Attorney for Youngrichskinny #FreeYoungRichSkinny\n' +
      '\n' +
      '\n' +
      'problematic..... on accident 😭💀',
    translator_type: 'none',
    protected: false,
    verified: false,
    followers_count: 161,
    friends_count: 121,
    listed_count: 0,
    favourites_count: 18294,
    statuses_count: 21612,
    created_at: 'Wed May 26 05:56:03 +0000 2021',
    utc_offset: null,
    time_zone: null,
    geo_enabled: false,
    lang: null,
    contributors_enabled: false,
    is_translator: false,
    profile_background_color: 'F5F8FA',
    profile_background_image_url: '',
    profile_background_image_url_https: '',
    profile_background_tile: false,
    profile_link_color: '1DA1F2',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    profile_image_url: 'http://pbs.twimg.com/profile_images/1443452038394916871/a_lOy-Qz_normal.jpg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/1443452038394916871/a_lOy-Qz_normal.jpg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/1397431274160144385/1633985119',
    default_profile: true,
    default_profile_image: false,
    following: null,
    follow_request_sent: null,
    notifications: null,
    withheld_in_countries: []
  },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  quote_count: 0,
  reply_count: 0,
  retweet_count: 0,
  favorite_count: 0,
  entities: {
    hashtags: [ [Object], [Object] ],
    urls: [],
    user_mentions: [],
    symbols: [],
    media: [ [Object] ]
  },
  extended_entities: { media: [ [Object] ] },
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  filter_level: 'low',
  lang: 'en',
  timestamp_ms: '1634698305563'
},
{
  created_at: 'Wed Oct 20 02:51:45 +0000 2021',
  id: 1450655952827338800,
  id_str: '1450655952827338757',
  text: 'RT @shepard_shtole: me, talking about my favorite characters: https://t.co/DM10HIKzY3',
  source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: {
    id: 3104042364,
    id_str: '3104042364',
    name: 'jen',
    screen_name: 'khadajen',
    location: '21 | she/her | 🇹🇭🇨🇳',
    url: 'https://nyahahenry.carrd.co/',
    description: '@Yanfeeds🧁 | fe lol gg etc | sometimes cosplay | thank u @tripwithjesus for the delicious terumi art 😔 | anjis milkers on strive',
    translator_type: 'none',
    protected: false,
    verified: false,
    followers_count: 89,
    friends_count: 375,
    listed_count: 1,
    favourites_count: 29032,
    statuses_count: 26029,
    created_at: 'Mon Mar 23 02:50:32 +0000 2015',
    utc_offset: null,
    time_zone: null,
    geo_enabled: true,
    lang: null,
    contributors_enabled: false,
    is_translator: false,
    profile_background_color: '000000',
    profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_tile: false,
    profile_link_color: 'FF3333',
    profile_sidebar_border_color: '000000',
    profile_sidebar_fill_color: '000000',
    profile_text_color: '000000',
    profile_use_background_image: false,
    profile_image_url: 'http://pbs.twimg.com/profile_images/1342295141063614470/iXCWdZDq_normal.jpg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/1342295141063614470/iXCWdZDq_normal.jpg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/3104042364/1605309325',
    default_profile: false,
    default_profile_image: false,
    following: null,
    follow_request_sent: null,
    notifications: null,
    withheld_in_countries: []
  },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  retweeted_status: {
    created_at: 'Mon Oct 18 21:31:12 +0000 2021',
    id: 1450212893027360800,
    id_str: '1450212893027360773',
    text: 'me, talking about my favorite characters: https://t.co/DM10HIKzY3',
    display_text_range: [ 0, 41 ],
    source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1336282872089620500,
      id_str: '1336282872089620481',
      name: 'ShepardShtole',
      screen_name: 'shepard_shtole',
      location: 'Normandy SR2',
      url: null,
      description: 'she/her, lvl25',
      translator_type: 'none',
      protected: false,
      verified: false,
      followers_count: 374,
      friends_count: 324,
      listed_count: 1,
      favourites_count: 6204,
      statuses_count: 3229,
      created_at: 'Tue Dec 08 12:14:14 +0000 2020',
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      profile_background_color: 'F5F8FA',
      profile_background_image_url: '',
      profile_background_image_url_https: '',
      profile_background_tile: false,
      profile_link_color: '1DA1F2',
      profile_sidebar_border_color: 'C0DEED',
      profile_sidebar_fill_color: 'DDEEF6',
      profile_text_color: '333333',
      profile_use_background_image: true,
      profile_image_url: 'http://pbs.twimg.com/profile_images/1444970693184180226/jesRfWlh_normal.jpg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/1444970693184180226/jesRfWlh_normal.jpg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/1336282872089620481/1619780357',
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      withheld_in_countries: []
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    quote_count: 918,
    reply_count: 18,
    retweet_count: 5672,
    favorite_count: 16695,
    entities: {
      hashtags: [],
      urls: [],
      user_mentions: [],
      symbols: [],
      media: [Array]
    },
    extended_entities: { media: [Array] },
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    filter_level: 'low',
    lang: 'en'
  },
  is_quote_status: false,
  quote_count: 0,
  reply_count: 0,
  retweet_count: 0,
  favorite_count: 0,
  entities: {
    hashtags: [],
    urls: [],
    user_mentions: [ [Object] ],
    symbols: [],
    media: [ [Object] ]
  },
  extended_entities: { media: [ [Object] ] },
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  filter_level: 'low',
  lang: 'en',
  timestamp_ms: '1634698305695'
}]



